#!/bin/bash
# Fake initctl command for Ubuntu images
case "$1" in
    status)
        exit 0
        ;;
    start|stop|restart)
        exit 0
        ;;
    *)
        echo "Unknown command: $1"
        exit 1
        ;;
esac