---
name: 21.10, impish

on:
  pull_request:
  push:
    paths:
      - 'ubuntu2110/**'
      - '.github/workflows/build-21.10.yml'
  schedule:
    - cron: '14 4,6 * * 1,6'
  workflow_dispatch:

jobs:
  # Test the image builds and works correctly.
  test:
    name: Test ubuntu2110
    # runs-on: ubuntu-latest
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest]

    steps:
      - uses: actions/checkout@v2

      - name: Test building image.
        run: cd ubuntu2110 && docker build -t docker-ubuntu-21-impish .

      - name: Run the built image.
        run: docker run --name test-container -d --privileged -v /sys/fs/cgroup:/sys/fs/cgroup:ro docker-ubuntu-21-impish

      # - name: Verify Ansible is accessible in the built image.
        # run: docker exec --tty test-container env TERM=xterm ansible --version

  # If on master branch, build and release image.
  release:
    name: Release
    runs-on: ubuntu-latest
    needs: test
    if: github.ref == 'refs/heads/main'

    steps:
      - uses: actions/checkout@v2
      - uses: docker/setup-qemu-action@v1
      - name: Set up Docker Buildx
        id: buildx
        uses: buluma/setup-buildx-action@0.1.0
      - name: Available platforms
        run: echo ${{ steps.buildx.outputs.platforms }}

      - name: Login to DockerHub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      # - name: Login to GitHub Container Registry
      #   uses: docker/login-action@v1
      #   with:
      #     registry: ghcr.io
      #     username: ${{ github.repository_owner }}
      #     password: ${{ secrets.GITHUB_TOKEN }}

      - name: Build and push image.
        uses: docker/build-push-action@v2
        with:
          context: ubuntu2204/
          file: ubuntu2204/Dockerfile
          platforms: linux/amd64,linux/arm/v7,linux/arm64/v8,linux/ppc64le,linux/s390x
          push: true
          tags: |
            ${{ github.repository }}:impish, ${{ github.repository }}:21.10, ${{ github.repository }}:impish-20220612
