---
name: 22.04, jammy 

on:
  pull_request:
  push:
    paths:
      - 'ubuntu2204/**'
      - '.github/workflows/build-22.04.yml'
  schedule:
    - cron: '40 *,* * * *'
  workflow_dispatch:

jobs:
  # Test the image builds and works correctly.
  test:
    name: Test ubuntu2204
    # runs-on: ubuntu-latest
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest]

    steps:
      - uses: actions/checkout@v2

      - name: Test building image.
        run: cd ubuntu2204 && docker build -t docker-ubuntu-22 .

      - name: Run the built image.
        run: docker run --name test-container -d --privileged -v /sys/fs/cgroup:/sys/fs/cgroup:ro docker-ubuntu-22

      # - name: Verify Ansible is accessible in the built image.
        # run: docker exec --tty test-container env TERM=xterm ansible --version

  # If on master branch, build and release image.
  release:
    name: Release
    runs-on: ubuntu-latest
    needs: test
    if: github.ref == 'refs/heads/main'

    steps:
      - uses: actions/checkout@v2
      - uses: docker/setup-qemu-action@v1
      - uses: docker/setup-buildx-action@v1

      - name: Login to DockerHub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      # - name: Login to GitHub Container Registry
      #   uses: docker/login-action@v1
      #   with:
      #     registry: ghcr.io
      #     username: ${{ github.repository_owner }}
      #     password: ${{ secrets.GITHUB_TOKEN }}

      - name: Build and push image.
        uses: docker/build-push-action@v2
        with:
          context: ubuntu2204/
          file: ubuntu2204/Dockerfile
          platforms: linux/amd64,linux/arm64, linux/arm32v7, linux/arm64v8
          push: true
          tags: |
            ${{ github.repository }}:22.04, ${{ github.repository }}:jammy, ${{ github.repository }}:jammy-20211122, ${{ github.repository }}:devel